import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Layout from '@/components/Layout'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { isUserValid } from './api/utilities'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const [postId, setPostId] = useState();
  const [username, setusername] = useState();
  const [password, setPassword] = useState();
  const [loginErrPopup, setLoginErrPopup] = useState('none');

  const handleOnChange = (e) => setPostId(e.target.value)
  const handleOnSubmit = (e) => {
    e.preventDefault();
    router.push(`./post/${postId}`)
  }

  const attemptloginUser = (e) => {
    e.preventDefault();
    if (isUserValid(username, password)) {
      setLoginErrPopup('none');
      router.push('sections/contacts');
    }
    else {
      setLoginErrPopup('block');
    }
  }

  const handleUsernameChange = (e) => setusername(e.target.value)
  const handlePasswordChange = (e) => setPassword(e.target.value)

  let listOfStaticOptions = [
    {
      path: '/contacts',
      title: 'Contacts',
      desc: 'Click here to navigate to the new Sample Path for Contacts'
    },
    {
      path: '/sample-option',
      title: 'Sample Option',
      desc: 'Click here to navigate to the new Sample Path for Sample-Options'
    }
  ]
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App - Aimal</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles.description}>
            <p>
              Get started by editing&nbsp;
              <code className={styles.code}>pages/index.js</code>
            </p>
            <div>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                By{' '}
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  className={styles.vercelLogo}
                  width={100}
                  height={24}
                  priority
                />
              </a>
            </div>
            <div style={{ display: 'blank', color: '#FFFFFF', backgroundColor: '#FF0000', float: 'right', display: loginErrPopup }}>
              <p>Invalid Username or password</p>
            </div>
          </div>

          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
          </div>
          <div>
            <form onSubmit={handleOnSubmit}>
              <input type="text" name="name" onChange={handleOnChange} />
            </form>
          </div>
          <div className={styles.grid}>
            {
              listOfStaticOptions.map(element => {
                return (
                  <Link
                    href={'/sections' + element.path}
                    className={styles.card}
                    rel="noopener noreferrer"
                  >
                    <h2>
                      {element.title} <span>-&gt;</span>
                    </h2>
                    <p>
                      {element.desc}
                    </p>
                  </Link>
                )
              })
            }
          </div>
          <div className="container">
            <form onSubmit={(e) => e.preventDefault()}>
              <div className="form-outline mb-4">
                <input type="text" id="form2Example1" className="form-control" onChange={handleUsernameChange}/>
                <label className="form-label" for="form2Example1">Username</label>
              </div>

              <div className="form-outline mb-4">
                <input type="password" id="form2Example2" className="form-control" onChange={handlePasswordChange} />
                <label className="form-label" for="form2Example2">Password</label>
              </div>
              <button className='btn btn-primary btn-block mb-4' onClick={attemptloginUser}>Login</button>
            </form>
          </div>
        </main>
      </Layout>
    </>
  )
}
