import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Layout from '@/components/Layout'
import { useRouter } from 'next/router'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const [postId, setPostId] = useState();
  const handleOnChange = (e) => setPostId(e.target.value)
  const handleOnSubmit = (e) => {
    e.preventDefault();
    router.push(`./post/${postId}`)
  }

  let listOfStaticOptions = [
    {
      path: '/contacts',
      title: 'Contacts',
      desc: 'Click here to navigate to the new Sample Path for Contacts'
    },
    {
      path: '/sample-option',
      title: 'Sample Option',
      desc: 'Click here to navigate to the new Sample Path for Sample-Options'
    }
  ]
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App - Aimal</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles.description}>
            <p>
              Get started by editing&nbsp;
              <code className={styles.code}>pages/index.js</code>
            </p>
            <div>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                By{' '}
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  className={styles.vercelLogo}
                  width={100}
                  height={24}
                  priority
                />
              </a>
            </div>
          </div>

          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
          </div>
          <div>
            <form onSubmit={handleOnSubmit}>
              <input type="text" name="name" onChange={handleOnChange} />
            </form>
          </div>
          <div className={styles.grid}>
            {
              listOfStaticOptions.map(element => {
                return (
                  <Link
                    href={element.path}
                    className={styles.card}
                    rel="noopener noreferrer"
                  >
                    <h2>
                      {element.title} <span>-&gt;</span>
                    </h2>
                    <p>
                      {element.desc}
                    </p>
                  </Link>
                )
              })
            }
          </div>
        </main>
      </Layout>
    </>
  )
}
